### ISSUE TITLE
match_pairs_sp.py

### ISSUE THREAD

**Issue by githubhupan** [ufukefe/IME#2]
Thank you for your excellent work. But I can't find match_pairs_sp.py in utils/Algorithm_Wrappers/SuperPoint. Can you help me solve this problem? Thank you.

**Comment by ufukefe** [comment]
Hi, thanks for reporting this. Unfortunately, forgot to add match_pairs_sp.py
I added descriptors_sp.py in utils/Algorithm_Wrappers/SuperPoint and modified install.sh accordingly.

You can create match_pairs_sp.py in Algorithms/SuperPoint by copying match_pairs.py and overwriting lines using descriptors_sp.py

Or you can just setup from scratch using fresh repository :)

**Comment by githubhupan** [comment]
I got it, Thanks for your reply!
